name: dotnet console app build

on:
  push:
    branches: [ main, develop, dotnet-publish ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Checkout the repository
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Specify the desired .NET SDK version

    - name: Display dotnet version
      run: dotnet --version

    - name: Restore dependencies
      run: dotnet restore ./OpenSim.sln

    - name: Build
      run: dotnet publish ./OpenSim.sln --configuration Release

#    - name: Discover test projects
#      id: find-tests
#      run: |
#        echo "::set-output name=has_tests::$(if ls **/*Tests/*.csproj 1> /dev/null 2>&1; then echo true; else echo false; fi)"
#    - name: Test (if present)
#      if: steps.find-tests.outputs.has_tests == 'true'
#      run: dotnet test ./OpenSim.sln --no-build --verbosity normal


#    - name: Run Tests
#      run: dotnet test --logger "trx;LogFileName=<TestResults.trx>"
#
#      - name: Create the package
#        run: dotnet pack --configuration Release <my project>
#      - name: Publish the package to GPR
#        run: dotnet nuget push <my project>/bin/Release/*.nupkg
#
#    - name: Publish the package to GPR
#      run: dotnet nuget push <my project>/bin/Release/*.nupkg
