name: dotnet console app build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Checkout the repository
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Specify the desired .NET SDK version

    - name: Display dotnet version
      run: dotnet --version

    - name: Restore dependencies
      run: dotnet restore ./Tranquillity.sln

    - name: Build
      run: dotnet build ./Tranquillity.sln --configuration Release

    - name: Tests
      run: dotnet test ./Tranquillity.sln --verbosity normal

    - name: Publish
      run: dotnet publish ./Tranquillity.sln --configuration Release -o ./publish


#      - name: Create the package
#        run: dotnet pack --configuration Release <my project>
#      - name: Publish the package to GPR
#        run: dotnet nuget push <my project>/bin/Release/*.nupkg
#
#    - name: Publish the package to GPR
#      run: dotnet nuget push <my project>/bin/Release/*.nupkg
